// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace JD.Writer.E2E.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Studio acceptance criteria")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class StudioAcceptanceCriteriaFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Studio acceptance criteria", "  Validate JD.Writer v1 acceptance criteria across UI and API flows.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Studio.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Studio.feature.ndjson", 28);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Command palette and slash suggestions are accessible")]
        public async global::System.Threading.Tasks.Task CommandPaletteAndSlashSuggestionsAreAccessible()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Command palette and slash suggestions are accessible", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.AndAsync("I open the command palette with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.ThenAsync("I should see the command palette", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
    await testRunner.WhenAsync("I close the command palette", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
    await testRunner.AndAsync("I type \"/summ\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.ThenAsync("I should see slash command suggestions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Plugin slash template inserts structured markdown")]
        public async global::System.Threading.Tasks.Task PluginSlashTemplateInsertsStructuredMarkdown()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Plugin slash template inserts structured markdown", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.AndAsync("I type \"/stand\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.ThenAsync("I should see slash command suggestions", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
    await testRunner.WhenAsync("I select slash command \"standup-template\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("the editor should contain \"## Daily Standup\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Local-first persistence survives reload")]
        public async global::System.Threading.Tasks.Task Local_FirstPersistenceSurvivesReload()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Local-first persistence survives reload", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.AndAsync("I set note title to \"E2E Local Persistence\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("I type \"# Persisted Note\\n\\n- should survive reload\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.AndAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.ThenAsync("the note title input should be \"E2E Local Persistence\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("the editor should contain \"# Persisted Note\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Settings page persists theme preference")]
        public async global::System.Threading.Tasks.Task SettingsPagePersistsThemePreference()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Settings page persists theme preference", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.WhenAsync("I open the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("settings title should contain \"Studio Settings\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
    await testRunner.WhenAsync("I choose settings theme preference \"dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.AndAsync("I save settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.ThenAsync("settings theme preference should be \"dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("document site theme should be \"dark\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Settings page persists voice interpretation scale")]
        public async global::System.Threading.Tasks.Task SettingsPagePersistsVoiceInterpretationScale()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Settings page persists voice interpretation scale", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
    await testRunner.WhenAsync("I open the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
    await testRunner.AndAsync("I choose settings voice mode \"raw\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("I set settings voice chunk length to 320", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync("I set settings voice chunk overlap to 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync("I save settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.ThenAsync("settings voice mode should be \"raw\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
    await testRunner.AndAsync("settings voice chunk length should be 320", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.AndAsync("settings voice chunk overlap should be 50", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Local model readiness wizard guides setup steps")]
        public async global::System.Threading.Tasks.Task LocalModelReadinessWizardGuidesSetupSteps()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Local model readiness wizard guides setup steps", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.WhenAsync("I open the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("local model wizard should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.WhenAsync("I advance local model wizard step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("local model wizard step label should contain \"Step 2 of\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.WhenAsync("I advance local model wizard step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.AndAsync("I refresh local readiness diagnostics", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.ThenAsync("local readiness badge should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Corrupted local state is recovered without a circuit crash")]
        public async global::System.Threading.Tasks.Task CorruptedLocalStateIsRecoveredWithoutACircuitCrash()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Corrupted local state is recovered without a circuit crash", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.AndAsync("I inject corrupted local workspace state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.ThenAsync("the studio title should contain \"Markdown Studio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Oversized local state does not break circuit initialization")]
        public async global::System.Threading.Tasks.Task OversizedLocalStateDoesNotBreakCircuitInitialization()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Oversized local state does not break circuit initialization", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 70
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
    await testRunner.AndAsync("I inject oversized local workspace state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.ThenAsync("the studio title should contain \"Markdown Studio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preview render theme can change without app theme shift")]
        public async global::System.Threading.Tasks.Task PreviewRenderThemeCanChangeWithoutAppThemeShift()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preview render theme can change without app theme shift", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
    await testRunner.AndAsync("I choose preview render theme \"terminal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.ThenAsync("preview render theme should be \"terminal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("preview should use render class \"preview-theme-terminal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.WhenAsync("I reload the page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("preview render theme should be \"terminal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
    await testRunner.AndAsync("preview should use render class \"preview-theme-terminal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("AI continue appends content in the editor")]
        public async global::System.Threading.Tasks.Task AIContinueAppendsContentInTheEditor()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AI continue appends content in the editor", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.AndAsync("I type \"# Continue Target\\n\\n- first line\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.AndAsync("I trigger AI continue from the toolbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.ThenAsync("editor content should be longer than before", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Client-only mode continues draft without API service")]
        public async global::System.Threading.Tasks.Task Client_OnlyModeContinuesDraftWithoutAPIService()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Client-only mode continues draft without API service", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 93
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 94
    await testRunner.GivenAsync("JD.Writer client-only mode is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.AndAsync("I type \"# Standalone mode\\n\\n- keep writing locally\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
    await testRunner.AndAsync("I trigger AI continue from the toolbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.ThenAsync("editor content should be longer than before", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice capture shortcut toggles and inserts transcript")]
        public async global::System.Threading.Tasks.Task VoiceCaptureShortcutTogglesAndInsertsTranscript()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice capture shortcut toggles and inserts transcript", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 100
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 101
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 102
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.AndAsync("I inject voice transcript \"voice dictated backlog item\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
    await testRunner.ThenAsync("the editor should contain \"voice dictated backlog item\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("voice status should contain \"Voice:\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice interim transcript appears at cursor before final cleanup")]
        public async global::System.Threading.Tasks.Task VoiceInterimTranscriptAppearsAtCursorBeforeFinalCleanup()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice interim transcript appears at cursor before final cleanup", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 110
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 111
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 114
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 115
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.WhenAsync("I inject interim voice transcript \"words should flow instantly\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("the editor should contain \"words should flow instantly\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
    await testRunner.WhenAsync("I finalize voice transcript \"words should flow instantly\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.ThenAsync("local state should include voice transcript and cleanup operations", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice capture toolbar toggle works")]
        public async global::System.Threading.Tasks.Task VoiceCaptureToolbarToggleWorks()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice capture toolbar toggle works", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 122
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.AndAsync("I toggle voice capture from the toolbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
    await testRunner.ThenAsync("the voice toolbar button should contain \"Mic (On)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 127
    await testRunner.WhenAsync("I toggle voice capture from the toolbar", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 128
    await testRunner.ThenAsync("the voice toolbar button should contain \"Mic (Off)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice cleanup attempt is recorded in layer history")]
        public async global::System.Threading.Tasks.Task VoiceCleanupAttemptIsRecordedInLayerHistory()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice cleanup attempt is recorded in layer history", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
    await testRunner.AndAsync("I inject voice transcript \"voice cleanup should run\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.ThenAsync("local state should include voice transcript and cleanup operations", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice raw mode bypasses AI cleanup operations")]
        public async global::System.Threading.Tasks.Task VoiceRawModeBypassesAICleanupOperations()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice raw mode bypasses AI cleanup operations", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 139
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 140
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 141
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 142
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
    await testRunner.AndAsync("I enable raw transcription mode in voice console", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
    await testRunner.AndAsync("I finalize voice transcript \"raw mode should keep this exact phrase\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 147
    await testRunner.ThenAsync("the editor should contain \"raw mode should keep this exact phrase\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 148
    await testRunner.AndAsync("local state should include voice transcript without cleanup operations", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice recordings are persisted for playback and review")]
        public async global::System.Threading.Tasks.Task VoiceRecordingsArePersistedForPlaybackAndReview()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice recordings are persisted for playback and review", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 150
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 151
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 152
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 155
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
    await testRunner.AndAsync("I inject interim voice transcript \"record this for playback\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
    await testRunner.AndAsync("I finalize voice transcript \"record this for playback\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
    await testRunner.ThenAsync("voice recording list should contain at least 1 recording", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 160
    await testRunner.AndAsync("local state should include voice recording artifacts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voice recordings are reviewable in persisted audit logs")]
        public async global::System.Threading.Tasks.Task VoiceRecordingsAreReviewableInPersistedAuditLogs()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voice recordings are reviewable in persisted audit logs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 162
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 163
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 164
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
    await testRunner.AndAsync("I enable voice test mode", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
    await testRunner.AndAsync("I place cursor at the end of the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
    await testRunner.AndAsync("I toggle voice capture with keyboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
    await testRunner.AndAsync("I inject interim voice transcript \"review log interim\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
    await testRunner.AndAsync("I finalize voice transcript \"review log finalized payload\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 170
    await testRunner.ThenAsync("plugin panel \"Voice Review\" should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 171
    await testRunner.AndAsync("local state should include voice session transcript events", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
    await testRunner.AndAsync("voice review panel should contain \"review log finalized payload\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("System dark theme variables are applied")]
        public async global::System.Threading.Tasks.Task SystemDarkThemeVariablesAreApplied()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("System dark theme variables are applied", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 174
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 175
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 176
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 177
    await testRunner.AndAsync("I emulate dark color scheme", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
    await testRunner.ThenAsync("app background variable should be \"#070c16\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Edit layers are persisted with diff and tone metrics")]
        public async global::System.Threading.Tasks.Task EditLayersArePersistedWithDiffAndToneMetrics()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Edit layers are persisted with diff and tone metrics", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 181
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 182
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 183
    await testRunner.AndAsync("I type \"# Layered Draft\\n\\n- checkpoint alpha\" in the editor", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 184
    await testRunner.ThenAsync("local state should contain note layers with diff and tone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 185
    await testRunner.AndAsync("plugin panel \"History QC\" should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Plugin panels are loaded from manifest")]
        public async global::System.Threading.Tasks.Task PluginPanelsAreLoadedFromManifest()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Plugin panels are loaded from manifest", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 187
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 188
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 189
    await testRunner.WhenAsync("I open the studio home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 190
    await testRunner.ThenAsync("plugin panel \"Risk Radar\" should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 191
    await testRunner.AndAsync("plugin panel \"Open Questions\" should be visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("API provider summary reports ollama preference")]
        public async global::System.Threading.Tasks.Task APIProviderSummaryReportsOllamaPreference()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("API provider summary reports ollama preference", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 193
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 194
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 195
    await testRunner.WhenAsync("I request API provider summary", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 196
    await testRunner.ThenAsync("provider preference should be \"ollama\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 197
    await testRunner.AndAsync("ollama should be configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Runtime provider summary includes native local fallback chain")]
        public async global::System.Threading.Tasks.Task RuntimeProviderSummaryIncludesNativeLocalFallbackChain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Runtime provider summary includes native local fallback chain", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 199
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 200
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 201
    await testRunner.WhenAsync("I request runtime API provider summary", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 202
    await testRunner.ThenAsync("provider order should include \"native-llama-gpu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 203
    await testRunner.AndAsync("provider order should include \"native-llama-cpu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 204
    await testRunner.AndAsync("provider summary should include hardware profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("AI API continue and slash endpoints return content")]
        public async global::System.Threading.Tasks.Task AIAPIContinueAndSlashEndpointsReturnContent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("AI API continue and slash endpoints return content", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 206
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 207
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 208
    await testRunner.WhenAsync("I request continuation for \"# Plan\\n\\n- First idea\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 209
    await testRunner.ThenAsync("continuation output should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 210
    await testRunner.WhenAsync("I execute slash command \"summarize\" for \"# Draft\\n\\nThis is a long paragraph to c" +
                        "ondense.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 211
    await testRunner.ThenAsync("slash command output should be returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Assist stream endpoint returns NDJSON chunks")]
        public async global::System.Threading.Tasks.Task AssistStreamEndpointReturnsNDJSONChunks()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Assist stream endpoint returns NDJSON chunks", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 213
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 214
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 215
    await testRunner.WhenAsync("I request assist stream for mode \"hints\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 216
    await testRunner.ThenAsync("assist stream should return at least 1 chunk", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Plugin prompt stream endpoint returns NDJSON chunks")]
        public async global::System.Threading.Tasks.Task PluginPromptStreamEndpointReturnsNDJSONChunks()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Plugin prompt stream endpoint returns NDJSON chunks", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 218
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 219
    await testRunner.GivenAsync("JD.Writer is running for e2e tests", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 220
    await testRunner.WhenAsync("I request assist stream with custom prompt for mode \"plugin-risks\" and prompt \"Li" +
                        "st concise delivery risks and mitigations.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 221
    await testRunner.ThenAsync("assist stream should return at least 1 chunk", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
